---
name: Question
description: Ask a usage or design question
labels: ["type:question"]
title: "[Q]: "

body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: Provide as much context as possible
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Helps us route to the right owners
      options:
        - API
        - Web UI
        - Data/ETL
        - DevOps/CI
        - Docs
    validations:
      required: false
