blank_issues_enabled: false
contact_links:
- name: Security reports
url: mailto:security@[YOUR-DOMAIN]
about: Please report vulnerabilities privately. If email isn't available, enable "Private vulnerability reporting" in repo settings.
